[package]
name = "servoshell"
version = "0.0.3"
authors = ["Paul Rouget <me@paulrouget.com>"]
description = "A basic servo-based browser"
build = "build.rs"

[dependencies]
gleam = "0.4"
open = "1.1.1"
log = "0.3"
libservo = { git = "https://github.com/servo/servo", rev = "5062dc5914" }
objc = {version = "0.2", optional = true}
objc-foundation = {version = "0.1", optional = true}
core-foundation = {version = "0.3", optional = true}
core-graphics = {version = "0.8", optional = true}
cocoa = {version = "^0.9.2", optional = true}
cgl = {version = "0.2", optional = true}
libc = {version = "0.2", optional = true}
glutin = {version = "0.9", optional = true}
winit = {version = "0.7", optional = true}
tinyfiledialogs = {version = "2.0", optional = true}


[features]
with-cocoa = ["objc", "objc-foundation", "core-foundation", "core-graphics", "cocoa", "cgl", "libc"]
with-glutin = ["glutin", "winit", "tinyfiledialogs"]
