[package]
name = "servoshell"
version = "0.1.0"
authors = ["Paul Rouget <me@paulrouget.com>"]
description = "A basic MacOS servo-based browser"
build = "build.rs"

[dependencies]
libc = "*"
gleam = "0.2"
cgl = "0.1"
open = "1.1.1"
log = "0.3"
simplelog = "0.4"
objc = "0.2"
objc-foundation = "*"
core-foundation = "0.2.3"
core-graphics = "0.3"
cocoa = "0.8"
libservo = {path = "../servo/components/servo"} # 217d0a6153 + paul/head_parsed_url + paul/follow-link + paul/winParams

[replace]
"cocoa:0.8.0" = { path = "../cocoa-rs/" } # paulrouget/servoshell
