[package]
name = "servoshell"
version = "0.0.2"
authors = ["Paul Rouget <me@paulrouget.com>"]
description = "A basic MacOS servo-based browser"
build = "build.rs"

[dependencies]
libc = "*"
gleam = "0.4"
cgl = "0.2"
open = "1.1.1"
log = "0.3"
objc = "0.2"
objc-foundation = "*"
core-foundation = "0.2.3"
core-graphics = "0.3"
cocoa = "^0.8.1"
libservo = { git = "https://github.com/servo/servo", rev = "93a513c06f" }

[replace]
"https://github.com/servo/servo#libservo:0.0.1" = { path = '../servo/components/servo' }
