[package]
name = "servoshell"
version = "0.0.2"
authors = ["Paul Rouget <me@paulrouget.com>"]
description = "A basic MacOS servo-based browser"
build = "build.rs"

[dependencies]
libc = "*"
gleam = "0.4"
cgl = "0.2"
open = "1.1.1"
log = "0.3"
objc = "*"
objc-foundation = "*"
core-foundation = "*"
core-graphics = "*"
cocoa = "^0.9.2"
# libservo = { git = "https://github.com/servo/servo" }
libservo = { path = '../servo/components/servo' }

# [replace]
# # This needs to be paulrouget's servo fork, branch attach-pipeline-2
# "https://github.com/servo/servo#libservo:0.0.1" = { path = '../servo/components/servo' }
