[package]
name = "servoshell"
version = "0.1.0"
authors = ["Paul Rouget <me@paulrouget.com>"]

[dependencies]
libc = "*"
objc = "0.2"
objc-foundation = "*"
gleam = "0.2"
winit = "0.5"
glutin = "0.7"
cocoa = "0.6"
euclid = "0.10.3"
libservo = {path = "../servo/components/servo"} # needs azure update and wr 0.15
style_traits = {path = "../servo/components/style_traits"}
servo_geometry = {path = "../servo/components/geometry"}

[dependencies.webrender_traits]
git = "https://github.com/servo/webrender"
default_features = false
version = "0.14.0"

[replace]
"winit:0.5.10" = { path = "../winit/" } # paulrouget/servoshell (fix segfault and keyboard)
"cocoa:0.6.0" = { path = "../cocoa-rs/" } # paulrouget/toolbar
"https://github.com/servo/webrender#0.15.0" = { path = "../webrender/webrender/" } # paulrouget/outOfWindowRendering
"https://github.com/servo/webrender#webrender_traits:0.14.0" = { path = "../webrender/webrender_traits/" }

