[package]
name = "servoshell"
version = "0.1.0"
authors = ["Paul Rouget <me@paulrouget.com>"]
description = "A basic MacOS servo-based browser"
build = "build.rs"

[dependencies]
libc = "*"
gleam = "0.2"
cgl = "0.1"
open = "1.1.1"
log = "0.3"
objc = "0.2"
objc-foundation = "*"
core-foundation = "0.2.3"
core-graphics = "0.3"
cocoa = { path = "../cocoa-rs/" } # paulrouget/appeararanceNames
libservo = {path = "../servo/components/servo"} # 9986b42333 + paul/head_parsed_url
